In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [14]:
colunas_infra = [
       'IN_AGUA_POTAVEL',
       'IN_ENERGIA_REDE_PUBLICA',
       'IN_ESGOTO_REDE_PUBLICA',
       'IN_BIBLIOTECA',
       'IN_LABORATORIO_CIENCIAS', 
       'IN_LABORATORIO_INFORMATICA',
       'IN_QUADRA_ESPORTES', 
       'IN_REFEITORIO', 
       'IN_SALA_DIRETORIA',
       'IN_SALA_ATENDIMENTO_ESPECIAL', 
       'IN_COMPUTADOR',
       'IN_INTERNET_APRENDIZAGEM', 
       'TP_REDE_LOCAL', 
       'QT_PROF_ADMINISTRATIVOS',
       'QT_PROF_ASSIST_SOCIAL', 
       'IN_ALIMENTACAO', 
       'IN_REGULAR']

In [4]:
df = pd.read_csv("microdados_ed_basica_2023.csv", encoding='latin1', sep=';')
df

C:\Users\camil\AppData\Local\Temp\ipykernel_23344\4237495559.py:1: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("microdados_ed_basica_2023.csv", encoding='latin1', sep=';')

,NU_ANO_CENSO,NO_REGIAO,CO_REGIAO,NO_UF,SG_UF,CO_UF,NO_MUNICIPIO,CO_MUNICIPIO,NO_REGIAO_GEOG_INTERM,CO_REGIAO_GEOG_INTERM,...,QT_TUR_BAS_D,QT_TUR_BAS_N,QT_TUR_BAS_EAD,QT_TUR_INF_INT,QT_TUR_INF_CRE_INT,QT_TUR_INF_PRE_INT,QT_TUR_FUND_INT,QT_TUR_FUND_AI_INT,QT_TUR_FUND_AF_INT,QT_TUR_MED_INT
0,2023,Norte,1,Rondônia,RO,11,Porto Velho,1100205,Porto Velho,1101,...,14.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
1,2023,Norte,1,Rondônia,RO,11,Porto Velho,1100205,Porto Velho,1101,...,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2023,Norte,1,Rondônia,RO,11,Porto Velho,1100205,Porto Velho,1101,...,38.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2023,Norte,1,Rondônia,RO,11,Porto Velho,1100205,Porto Velho,1101,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2023,Norte,1,Rondônia,RO,11,Porto Velho,1100205,Porto Velho,1101,...,27.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217620,2023,Centro-Oeste,5,Distrito Federal,DF,53,Brasília,5300108,Distrito Federal,5301,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
217621,2023,Centro-Oeste,5,Distrito Federal,DF,53,Brasília,5300108,Distrito Federal,5301,...,22.0,0.0,0.0,4.0,3.0,1.0,0.0,0.0,0.0,0.0
217622,2023,Centro-Oeste,5,Distrito Federal,DF,53,Brasília,5300108,Distrito Federal,5301,...,16.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
217623,2023,Centro-Oeste,5,Distrito Federal,DF,53,Brasília,5300108,Distrito Federal,5301,...,24.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
217624,2023,Centro-Oeste,5,Distrito Federal,DF,53,Brasília,5300108,Distrito Federal,5301,...,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
print(df.columns)

Index(['NU_ANO_CENSO', 'NO_REGIAO', 'CO_REGIAO', 'NO_UF', 'SG_UF', 'CO_UF',
       'NO_MUNICIPIO', 'CO_MUNICIPIO', 'NO_REGIAO_GEOG_INTERM',
       'CO_REGIAO_GEOG_INTERM',
       ...
       'QT_TUR_BAS_D', 'QT_TUR_BAS_N', 'QT_TUR_BAS_EAD', 'QT_TUR_INF_INT',
       'QT_TUR_INF_CRE_INT', 'QT_TUR_INF_PRE_INT', 'QT_TUR_FUND_INT',
       'QT_TUR_FUND_AI_INT', 'QT_TUR_FUND_AF_INT', 'QT_TUR_MED_INT'],
      dtype='object', length=408)

In [6]:
df['NO_REGIAO']

0                Norte
1                Norte
2                Norte
3                Norte
4                Norte
              ...
217620    Centro-Oeste
217621    Centro-Oeste
217622    Centro-Oeste
217623    Centro-Oeste
217624    Centro-Oeste
Name: NO_REGIAO, Length: 217625, dtype: object

In [7]:
sudeste = df[df['NO_REGIAO'] == 'Sudeste']
sudeste

,NU_ANO_CENSO,NO_REGIAO,CO_REGIAO,NO_UF,SG_UF,CO_UF,NO_MUNICIPIO,CO_MUNICIPIO,NO_REGIAO_GEOG_INTERM,CO_REGIAO_GEOG_INTERM,...,QT_TUR_BAS_D,QT_TUR_BAS_N,QT_TUR_BAS_EAD,QT_TUR_INF_INT,QT_TUR_INF_CRE_INT,QT_TUR_INF_PRE_INT,QT_TUR_FUND_INT,QT_TUR_FUND_AI_INT,QT_TUR_FUND_AF_INT,QT_TUR_MED_INT
101846,2023,Sudeste,3,Minas Gerais,MG,31,Belo Horizonte,3106200,Belo Horizonte,3101,...,41.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41.0
101847,2023,Sudeste,3,Minas Gerais,MG,31,Belo Horizonte,3106200,Belo Horizonte,3101,...,19.0,4.0,0.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0
101848,2023,Sudeste,3,Minas Gerais,MG,31,Belo Horizonte,3106200,Belo Horizonte,3101,...,39.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101849,2023,Sudeste,3,Minas Gerais,MG,31,Belo Horizonte,3106200,Belo Horizonte,3101,...,12.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,4.0,2.0
101850,2023,Sudeste,3,Minas Gerais,MG,31,Belo Horizonte,3106200,Belo Horizonte,3101,...,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177499,2023,Sudeste,3,São Paulo,SP,35,Santa Fé do Sul,3546603,São José do Rio Preto,3507,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177500,2023,Sudeste,3,São Paulo,SP,35,Franca,3516200,Ribeirão Preto,3508,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177501,2023,Sudeste,3,São Paulo,SP,35,Fernandópolis,3515509,São José do Rio Preto,3507,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177502,2023,Sudeste,3,São Paulo,SP,35,Igaraçu do Tietê,3520004,Bauru,3503,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177503,2023,Sudeste,3,São Paulo,SP,35,São Paulo,3550308,São Paulo,3501,...,25.0,21.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
df_novo = df[['NO_REGIAO', 'TP_SITUACAO_FUNCIONAMENTO',
       'IN_AGUA_POTAVEL', 'IN_ENERGIA_REDE_PUBLICA', 'IN_ESGOTO_REDE_PUBLICA',
       'IN_LIXO_SERVICO_COLETA', 'IN_BIBLIOTECA', 'IN_BIBLIOTECA_SALA_LEITURA',
       'IN_COZINHA', 'IN_LABORATORIO_CIENCIAS', 'IN_LABORATORIO_INFORMATICA',
       'IN_PATIO_COBERTO', 'IN_PATIO_DESCOBERTO', 'IN_PARQUE_INFANTIL',
       'IN_QUADRA_ESPORTES', 'IN_REFEITORIO', 'IN_SALA_DIRETORIA',
       'IN_SALA_ATENDIMENTO_ESPECIAL', 'IN_COMPUTADOR',
       'IN_INTERNET_APRENDIZAGEM', 'TP_REDE_LOCAL', 'QT_PROF_ADMINISTRATIVOS',
       'IN_PROF_ADMINISTRATIVOS', 'IN_PROF_ASSIST_SOCIAL',
       'QT_PROF_ASSIST_SOCIAL', 'IN_ALIMENTACAO', 'IN_REGULAR']]

In [9]:
df_novo

,NO_REGIAO,TP_SITUACAO_FUNCIONAMENTO,IN_AGUA_POTAVEL,IN_ENERGIA_REDE_PUBLICA,IN_ESGOTO_REDE_PUBLICA,IN_LIXO_SERVICO_COLETA,IN_BIBLIOTECA,IN_BIBLIOTECA_SALA_LEITURA,IN_COZINHA,IN_LABORATORIO_CIENCIAS,...,IN_SALA_ATENDIMENTO_ESPECIAL,IN_COMPUTADOR,IN_INTERNET_APRENDIZAGEM,TP_REDE_LOCAL,QT_PROF_ADMINISTRATIVOS,IN_PROF_ADMINISTRATIVOS,IN_PROF_ASSIST_SOCIAL,QT_PROF_ASSIST_SOCIAL,IN_ALIMENTACAO,IN_REGULAR
0,Norte,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,...,1.0,1.0,1.0,2.0,1.0,1.0,0.0,0.0,1.0,1.0
1,Norte,1,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,...,1.0,1.0,1.0,3.0,1.0,1.0,0.0,0.0,1.0,1.0
2,Norte,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,1.0,3.0,8.0,1.0,0.0,0.0,0.0,1.0
3,Norte,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,...,0.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0
4,Norte,1,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,1.0,1.0,3.0,2.0,1.0,1.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217620,Centro-Oeste,1,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,3.0,2.0,1.0,0.0,0.0,0.0,1.0
217621,Centro-Oeste,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,1.0,3.0,88888.0,1.0,1.0,1.0,0.0,1.0
217622,Centro-Oeste,1,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,...,0.0,1.0,1.0,1.0,3.0,1.0,0.0,0.0,0.0,1.0
217623,Centro-Oeste,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,1.0,3.0,1.0,1.0,0.0,0.0,0.0,1.0
217624,Centro-Oeste,1,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,0.0,1.0

In [10]:
# norte = df_novo[df_novo['NO_REGIAO'].str.strip().str.lower() == 'sudeste']
print(df_novo.shape)

(217625, 27)

In [11]:
df_novo.isnull().sum()

NO_REGIAO                           0
TP_SITUACAO_FUNCIONAMENTO           0
IN_AGUA_POTAVEL                 37395
IN_ENERGIA_REDE_PUBLICA         37395
IN_ESGOTO_REDE_PUBLICA          37395
IN_LIXO_SERVICO_COLETA          37395
IN_BIBLIOTECA                   37395
IN_BIBLIOTECA_SALA_LEITURA      37395
IN_COZINHA                      37395
IN_LABORATORIO_CIENCIAS         37395
IN_LABORATORIO_INFORMATICA      37395
IN_PATIO_COBERTO                37395
IN_PATIO_DESCOBERTO             37395
IN_PARQUE_INFANTIL              37395
IN_QUADRA_ESPORTES              37395
IN_REFEITORIO                   37395
IN_SALA_DIRETORIA               37395
IN_SALA_ATENDIMENTO_ESPECIAL    37395
IN_COMPUTADOR                   37395
IN_INTERNET_APRENDIZAGEM        37395
TP_REDE_LOCAL                   37395
QT_PROF_ADMINISTRATIVOS         37395
IN_PROF_ADMINISTRATIVOS         37395
IN_PROF_ASSIST_SOCIAL           37395
QT_PROF_ASSIST_SOCIAL           37395
IN_ALIMENTACAO                  37395
IN_REGULAR                      37395
dtype: int64

In [12]:
df_novo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 217625 entries, 0 to 217624
Data columns (total 27 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   NO_REGIAO                     217625 non-null  object
 1   TP_SITUACAO_FUNCIONAMENTO     217625 non-null  int64
 2   IN_AGUA_POTAVEL               180230 non-null  float64
 3   IN_ENERGIA_REDE_PUBLICA       180230 non-null  float64
 4   IN_ESGOTO_REDE_PUBLICA        180230 non-null  float64
 5   IN_LIXO_SERVICO_COLETA        180230 non-null  float64
 6   IN_BIBLIOTECA                 180230 non-null  float64
 7   IN_BIBLIOTECA_SALA_LEITURA    180230 non-null  float64
 8   IN_COZINHA                    180230 non-null  float64
 9   IN_LABORATORIO_CIENCIAS       180230 non-null  float64
 10  IN_LABORATORIO_INFORMATICA    180230 non-null  float64
 11  IN_PATIO_COBERTO              180230 non-null  float64
 12  IN_PATIO_DESCOBERTO           180230 non-null  float64
 13  IN_PARQUE_INFANTIL            180230 non-null  float64
 14  IN_QUADRA_ESPORTES            180230 non-null  float64
 15  IN_REFEITORIO                 180230 non-null  float64
 16  IN_SALA_DIRETORIA             180230 non-null  float64
 17  IN_SALA_ATENDIMENTO_ESPECIAL  180230 non-null  float64
 18  IN_COMPUTADOR                 180230 non-null  float64
 19  IN_INTERNET_APRENDIZAGEM      180230 non-null  float64
 20  TP_REDE_LOCAL                 180230 non-null  float64
 21  QT_PROF_ADMINISTRATIVOS       180230 non-null  float64
 22  IN_PROF_ADMINISTRATIVOS       180230 non-null  float64
 23  IN_PROF_ASSIST_SOCIAL         180230 non-null  float64
 24  QT_PROF_ASSIST_SOCIAL         180230 non-null  float64
 25  IN_ALIMENTACAO                180230 non-null  float64
 26  IN_REGULAR                    180230 non-null  float64
dtypes: float64(25), int64(1), object(1)
memory usage: 44.8+ MB

In [13]:
df_dummies = pd.get_dummies(df_novo, columns=['NO_REGIAO'])
df_dummies

,TP_SITUACAO_FUNCIONAMENTO,IN_AGUA_POTAVEL,IN_ENERGIA_REDE_PUBLICA,IN_ESGOTO_REDE_PUBLICA,IN_LIXO_SERVICO_COLETA,IN_BIBLIOTECA,IN_BIBLIOTECA_SALA_LEITURA,IN_COZINHA,IN_LABORATORIO_CIENCIAS,IN_LABORATORIO_INFORMATICA,...,IN_PROF_ADMINISTRATIVOS,IN_PROF_ASSIST_SOCIAL,QT_PROF_ASSIST_SOCIAL,IN_ALIMENTACAO,IN_REGULAR,NO_REGIAO_Centro-Oeste,NO_REGIAO_Nordeste,NO_REGIAO_Norte,NO_REGIAO_Sudeste,NO_REGIAO_Sul
0,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,...,1.0,0.0,0.0,1.0,1.0,False,False,True,False,False
1,1,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,1.0,False,False,True,False,False
2,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,1.0,False,False,True,False,False
3,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,False,False,True,False,False
4,1,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,...,1.0,1.0,1.0,0.0,1.0,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217620,1,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,True,False,False,False,False
217621,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,0.0,1.0,True,False,False,False,False
217622,1,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,...,1.0,0.0,0.0,0.0,1.0,True,False,False,False,False
217623,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,1.0,True,False,False,False,False
217624,1,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,0.0,1.0,True,False,False,False,False